networks:
  internal:
    internal: true
  external:
    driver: bridge
  

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    networks:
      - internal
      
  # celery:
  #   image: tai-django-web
  #   container_name: cinema_celery
  #   command: celery -A backend_project worker -l info
  #   depends_on:
  #     - db
  #     - redis
  #     - backend
  #   networks:
  #     - internal
  #     - external
  #   env_file:
  #     - .env
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   volumes:
  #     - ${FIREBASE_CREDENTIALS_HOST_PATH}:/app

  backend:
    image: tai-django-web
    container_name: cinema_backend
    ports:
      - 8000:8000
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ${FIREBASE_CREDENTIALS_HOST_PATH}:/app/
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    env_file:
      - .env
    networks:
      - internal
      - external

  frontend:
    image: tai-frontend
    container_name: cinema_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    env_file:
      - .env
    networks:
      - internal
      - external    

volumes:
  postgres_data: