# Generated by Django 5.1.7 on 2025-05-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_api', '0011_movieshowing_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tickets', models.ManyToManyField(to='cinema_api.ticket')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentstatus')),
            ],
        ),
    ]
