# Generated by Django 5.1.7 on 2025-04-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahalls',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='movies',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_api.moviecrews'),
        ),
    ]
