# Generated by Django 5.1.7 on 2025-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0002_rename_type_cinemahalls_types_movies_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshowings',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
