# Generated by Django 5.1.7 on 2025-04-25 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0003_alter_movieshowings_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cinemahalls',
            constraint=models.UniqueConstraint(fields=('cinema', 'hall_number'), name='unique_cinema_hall'),
        ),
        migrations.AddConstraint(
            model_name='movieshowings',
            constraint=models.UniqueConstraint(fields=('movie', 'date', 'hall'), name='unique_showing'),
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.UniqueConstraint(fields=('showing', 'seat'), name='unique_ticket'),
        ),
    ]
