# Generated by Django 5.1.7 on 2025-04-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0004_cinemahalls_unique_cinema_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='crew',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_api.moviecrews'),
        ),
    ]
