# Generated by Django 5.1.7 on 2025-05-03 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0005_alter_movies_crew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Cinemas',
            new_name='Cinema',
        ),
        migrations.RenameModel(
            old_name='CinemaHalls',
            new_name='CinemaHall',
        ),
        migrations.RenameModel(
            old_name='HallTypes',
            new_name='HallType',
        ),
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='MovieCrews',
            new_name='MovieCrew',
        ),
        migrations.RenameModel(
            old_name='MovieShowings',
            new_name='MovieShowing',
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('trailer', models.URLField(blank=True, null=True)),
                ('crew', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_api.moviecrew')),
            ],
        ),
        migrations.AlterField(
            model_name='movieshowing',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_api.movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
