# Generated by Django 5.1.7 on 2025-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0006_rename_artists_artist_rename_cinemas_cinema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecrew',
            name='director',
        ),
        migrations.AddField(
            model_name='moviecrew',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director', to='cinema_api.artist'),
        ),
    ]
