# Generated by Django 5.1.7 on 2025-05-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0008_genre_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
    ]
