# Generated by Django 5.1.7 on 2025-11-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0012_ticket_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
