# Generated by Django 5.1.7 on 2025-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0012_ticket_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='logitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
