# Generated by Django 5.1.7 on 2025-06-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0013_cinema_latitude_cinema_logitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
